//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.1
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STA.Carichi.Sisma.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STA.Carichi.Sisma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ;;;TR=30;;;TR=50;;;TR=72;;;TR=101;;;TR=140;;;TR=201;;;TR=475;;;TR=975;;;TR=2475;;
        ///ID;LON;LAT;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*;ag;Fo;TC*
        ///4977;12.17004;47.17786;0.124;2.22;0.13;0.164;2.48;0.14;0.194;2.49;0.18;0.231;2.47;0.2;0.269;2.44;0.22;0.308;2.46;0.28;0.401;2.66;0.34;0.494;2.79;0.37;0.617;2.96;0.4
        ///5196;11.95148;47.12534;0.123;2.21;0.13;0.164;2.46;0.14;0.194;2.47;0.18;0.23;2.47;0.2;0.266;2.45;0.23;0.305;2.47;0.28;0.397;2.66;0.34;0.488;2.78;0.37;0.608;2.96;0 [stringa troncata]&quot;;.
        /// </summary>
        internal static string TabellaParametriSpettrali {
            get {
                return ResourceManager.GetString("TabellaParametriSpettrali", resourceCulture);
            }
        }
    }
}
